networks:
  default: avax-main
  avax-main:
    host: ${AVAX_RPC_URL}
alpha-homora:
  HomoraBank: "0x376d16C7dE138B01455a51dA79AD65806E9cd694"
  HomoraBankABI: "HomoraBankABI.json"    
  pools:
    USDC.e/AVAX:
      token0: "0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664"
      token1: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
      spell: "0xdbc2aa11aa01baa22892de745c661db9f204b2cd"
      spell_abi: "TraderJoeSpellV1ABI.json"
dotenv: .env
wallets:
  private_key: ${PRIVATE_KEY}
